app/mod_auth/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
    flash, g, session, redirect, url_for

from app.mod_auth.models import User

# Import module forms
from app.mod_auth.forms import LoginForm, SignupForm

# Define the blueprint: 'catalog', set its url prefix: app.url/catalog
mod_auth = Blueprint('auth', __name__, url_prefix='/auth')


# Interaction with user entity of the database
from app.mod_auth.repositories import UserRepository

# Helpers to set login session common information
from app.mod_auth.helpers import set_base_login_session, \
    login_session, generate_CSRF_token, BASIC_PROVIDER

from app import db


@mod_auth.route('/login', methods=['GET', 'POST'])
def show_signin():
     # If sign in form is submitted
    form = LoginForm(request.form)

    # Verify the sign in form
    if form.validate_on_submit():
        repo = UserRepository(db.session)
        user = repo.find_by_username(form.username.data)
        if (user and user.verify_password(form.password.data)):
            set_base_login_session(user,  BASIC_PROVIDER)
            return redirect(url_for('index'))
        else:
            flash('User or password is invalid!')

    # Anti Cross-site request forgery token
    state = generate_CSRF_token()
    login_session['STATE'] = state

    return render_template("auth/signin.html",
                           form=form,
                           STATE=state)


@mod_auth.route('/signup', methods=['GET', 'POST'])
def show_signup():
    # If signup in form is submitted
    form = SignupForm(request.form)

    # Verify the signup in form
    if form.validate_on_submit():
        try:
            repo = UserRepository(db.session)
            if repo.has_by_username(form.name.data):
                flash('Username is already registered')
            else:  # Persist user and redirect to catalog page
                user = User()
                user.name = form.name.data
                user.username = form.username.data
                user.hash_password(form.password.data)
                repo.add(user)
                repo.commit()
                return redirect(url_for('index'))
        except:
            flash('Fail save user in database :(')

    return render_template("auth/signup.html", form=form)

app/templates/template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Catalog App - Udacity project">
    <meta name="author" content="Denis Marques">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Catalog</title>
    <!-- Google sign api -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="//apis.google.com/js/platform.js?onload=start"></script>
    <!-- End Google sign api -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/site.css')}}">
</head>

<body>
    <div class="main-container">
        <header role="heading">
            <div class="center-container header-container">
                <div class="brand-container">
                    <a class="brand" href="{{ url_for('catalog.show') }}">
                        Catalog App
                    </a>
                </div>
                <nav>
                    <!--TODO: 'username' in login_session >> is not update all the time--> 
                    {% if user_is_logged() %}
                        <div class="logout-container">
                            <span class="user-name"> Welcome <strong>{{ get_welcome_user() }}</strong> :)</span>
                            <a class="button button-header" onclick="logout()">Logout</a>
                        </div>
                    {% else %}
                        <a class="button button-header" href="{{ url_for('auth.show_signin') }}">Login</a>
                    {% endif %}
                </nav>
            </div>
        </header>
        <main>
            {% block body %}
            {% endblock %}
        </main>

    </div>

    <script>
        function logout() {
            $.ajax({
                type: 'POST',
                url: '/api/v1/auth/logout',
                success: function (result) {
                    if (result) {
                        window.location.href = "/catalog";
                    } else {
                        $('#result').html('Failed to log out.');
                    }
                }
            });
        }

        /*
       * Open the drawer when the menu ison is clicked.
       */
        var menu = document.querySelector('#menu');
        var main = document.querySelector('main');
        var drawer = document.querySelector('.categories');

        menu.addEventListener('click', function (e) {
            drawer.classList.toggle('open');
            e.stopPropagation();

        });
        main.addEventListener('click', function () {
            drawer.classList.remove('open');
        });
    </script>
</body>

</html>